django_ex/urls.py
from django.urls import path, include
from django.contrib.auth.decorators import permission_required
from . import views


# app_name을 지정해주면 template에 {% url %}에도 app_name을 명시해야함 ex-{% url 'appname:name' %}
app_name = 'django_ex'
urlpatterns = [
    path('', views.HomeView.as_view(), name='home'),
    path('docs/<int:current_user>/', views.document_list, name='document_list'),
    path('docs/<int:current_user>/<int:current_ceo>/', views.document_post, name='document_post'),
    path('docs/<int:current_user>/<int:current_ceo>/results/', views.document_results, name='document_results'),
    path('presentation/<int:current_user>/', views.presentation_list, name='presentation_list'),
    path('manager/base_info_list/', views.BaseListView.as_view(), name='base_info_list'),
    path('manager/base-info-change/<int:current_ceo>/', views.base_info_change, name='base-info-change'),
    path('manager/base-info-check/', views.base_info_check, name='base-info-check'),
    path('manager/input/', views.base_info, name='base_info'),
    path('show-results/<int:current_user>/', views.checked_evaluation, name='checked-evaluation'),
    path('change-results/<int:current_user>/<int:current_ceo>/', views.changed_evaluation, name='changed-evaluation'),
    path('docs/발표평가-1차/', views.TestListView.as_view(), name='test_list'),
    path('docs/발표평가-1차/평가목록/', views.select_year, name='select_year'),
    path('docs/발표평가-1차/종합결과/', views.test_total_results, name='test_total_results'),
    path('docs/발표평가-1차/평가결과목록/', views.select_year_results, name='select_year_results'),
    path('docs/발표평가-1차/발표차수/', views.select_th, name='select_th'),
]

ex/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('django_ex.urls')),
    path('django_ex/', include('django.contrib.auth.urls')),
]

django_ex/models.py
from django.conf import settings
from django.db import models
import datetime
from django.contrib.auth.models import User, AbstractUser


# Create your models here.
class MyUser(AbstractUser):
    pass

class Ceo(models.Model):
    ITEM_FIELDS_SELECT=(
        ('기술분야','기술분야'),
        ('BM분야','BM분야'),
    )
    WORK_FIELDS_SELECT=(
        ('제조업','제조업'),
        ('서비스업','서비스업'),
    )
    SETUP_FIELDS_SELECT=(
        ('기창업','기창업'),
        ('창업','창업'),
    )
    YEARS=(
        (2019, 2019),
        (2020, 2020),
        (2021, 2021),
    )
    ceoname = models.CharField(max_length=30, blank=False)
    years = models.IntegerField(choices=YEARS, blank=False, default=datetime.datetime.now().year)
    item_fields = models.CharField(choices=ITEM_FIELDS_SELECT, max_length=30, blank=False)
    work_fields = models.CharField(choices=WORK_FIELDS_SELECT, max_length=30, blank=False)
    setup_fields = models.CharField(choices=SETUP_FIELDS_SELECT, max_length=30, blank=False)
    plus_points = models.FloatField(null=False, blank=True, default=0.0)
    itemname = models.CharField(max_length=200, blank=False, unique=True)
    ceo_relation = models.ManyToManyField(MyUser, through='Score')

    def __str__(self):
        return self.ceoname

class Score(models.Model):
    TH_SELECT = (
        ('1차','1차'),
        ('2차','2차'),
    )
    myuser = models.ForeignKey(MyUser, on_delete=models.CASCADE)
    ceo = models.ForeignKey(Ceo, on_delete=models.CASCADE, related_name='related_ceo')
    th = models.CharField(choices=TH_SELECT, max_length=20, blank=False)
    score_0 = models.IntegerField(null=False)
    score_1 = models.IntegerField(null=False)
    score_2 = models.IntegerField(null=False)
    score_3 = models.IntegerField(null=False)
    score_4 = models.IntegerField(null=False)
    score_5 = models.IntegerField(null=False)
    score_6 = models.IntegerField(null=False)
    score_7 = models.IntegerField(null=False)
    # score_8 = models.IntegerField(null=False)
    comment = models.TextField(default="", null=False)
    # subtotal = models.IntegerField(null=True, blank=True)
    # total = models.IntegerField(null=True, blank=True)
    create_date = models.DateTimeField(auto_now_add=True)
    updated_date = models.DateTimeField(auto_now=True)

    def __str__(self):
        return '{} {}'.format(self.id, self.ceo)
        # return "self.{}".format(self.ceo) - self까지 반환하면 에러남 (__str__ returned non-string (type int))

    class Meta:
        unique_together = (
            ('myuser', 'ceo',),
            )

django_ex/forms.py
from django.contrib.auth import forms

from .models import MyUser, Ceo, Score


# class CeoForm(forms.Form):
#     ITEM_FIELDS_CHOICES = ('기술분야', 'BM분야')
#     WORK_FIELDS_CHOICES = ('제조업', '서비스업')
#     SETUP_FIELDS_CHOICES = ('기창업', '창업')
#
#     item_fields = forms.CharField(wiget=forms.RadioSelect, choices=ITEM_FIELDS_CHOICES, required=True)
#     work_fields = forms.CharField(wiget=forms.RadioSelect, choices=WORK_FIELDS_CHOICES, required=True)
#     setup_fields = forms.CharField(wiget=forms.RadioSelect, choices=SETUP_FIELDS_CHOICES, required=True)

django_ex/views.py
# from django.shortcuts import render, render_to_response, get_object_or_404, reverse, redirect
# from django import forms
# from django.core.exceptions import ValidationError, MultipleObjectsReturned, ObjectDoesNotExist
# from django.db.utils import IntegrityError
# from django.contrib.auth.forms import UserCreationForm
# from django.http import Http404, HttpResponse, HttpResponseRedirect, JsonResponse
# from django.contrib import messages
# from django.views.generic.base import TemplateView
# from django.views.generic.edit import FormView
# from django.views.generic import ListView
# from .models import Ceo, MyUser, Score
# from . import models
#
#
# class ScoreForm(forms.ModelForm):
#     score_0 = forms.IntegerField()
#     score_1 = forms.IntegerField()
#     score_2 = forms.IntegerField()
#     score_3 = forms.IntegerField()
#     score_4 = forms.IntegerField()
#     score_5 = forms.IntegerField()
#     score_6 = forms.IntegerField()
#     score_7 = forms.IntegerField()
#     score_8 = forms.IntegerField()
#     comment = forms.CharField(widget=forms.Textarea)
#
#     class Meta:
#         model = Score
#         exclude = ('ceo', 'myuser')
#
# # clean은 필드의 서브클래스로 폼의 전체필드에 대해 유효성 검사를 할 때 사용하고, clean_필드명 함수는 폼의 서브클래스로 특정 필드에 대한 유효성 검사를 실시할 때 사용한다. 폼에 두 메서드가 같이 있을 땐 clean_필드명 메서드가 먼저 실행된다.
# #     def clean(self):
# #         cleaned_data = self.cleaned_data
# #
# # # socre_0 = self.cleaned_data.get()는 clean() 메소드에서 자꾸 오류가 난다.. cleaned_data[]로 데이터 변화값을 받아줘야한다.
# #         score_0 = cleaned_data.get('score_0')
# #         score_1 = cleaned_data.get('score_1')
# #         score_2 = cleaned_data.get('score_2')
# #         score_3 = cleaned_data.get('score_3')
# #         score_4 = cleaned_data.get('score_4')
# #         score_5 = cleaned_data.get('score_5')
# #         score_6 = cleaned_data.get('score_6')
# #         score_7 = cleaned_data.get('score_7')
# #         score_8 = cleaned_data.get('score_8')
# #         comment = cleaned_data.get('comment')
#
#
#         def clean_score_0(self):
#             score_0 = self.cleaned_data.get('score_0')
#             return score_0
#         def clean_score_1(self):
#             score_1 = self.cleaned_data.get('score_1')
#             return score_1
#         def clean_score_2(self):
#             score_2 = self.cleaned_data.get('score_2')
#             return score_2
#         def clean_score_3(self):
#             score_3 = self.cleaned_data.get('score_3')
#             return score_3
#         def clean_score_4(self):
#             score_4 = self.cleaned_data.get('score_4')
#             return score_4
#         def clean_score_5(self):
#             score_5 = self.cleaned_data.get('score_5')
#             return score_5
#         def clean_score_6(self):
#             score_6 = self.cleaned_data.get('score_6')
#             return score_6
#         def clean_score_7(self):
#             score_7 = self.cleaned_data.get('score_7')
#             return score_7
#         def clean_score_8(self):
#             score_8 = self.cleaned_data.get('score_8')
#             return score_8
#         def clean_comment(self):
#             comment = self.cleaned_data.get('comment')
#             return comment
#
#         def save(self):
#             score = super().save(commit=False)
#             if 0 <= score_0 <= 15 and 0 <= score_1 <= 15 and 0 <= score_2 <= 15 and 0 <= score_3 <= 15 and 0 <= score_4 <= 5 and 0 <= score_6 <= 5 and 0 <= score_5 <= 10 and 0 <= score_7 <= 10   and 0 <= score_8 <= 10:
#                 score.save(commit=True)
#                 # return cleaned_data
#             else:
#                 raise forms.ValidationError("점수를 확인해주세요.", code='too mach')
#                 # return cleaned_data
#
# # 지원자 정보 확인할 때 choicefield에 지원자명을 나타내주는 폼
# class CheckCeoForm(forms.Form):
#     # 모델의 필드값을 choicefield로 만들기 - 데이터가 안넘어옴 > ModelChoiceField를 올바른 방법으로 사용하지 않은 것 같음.
#     # ceo_select = Ceo.objects.values_list('ceoname',flat=True).order_by('ceoname')
#     # ceos = forms.ModelChoiceField(queryset=ceo_select)
#
#     YEARS=(
#         (2019, 2019),
#         (2020, 2020),
#         (2021, 2021),
#         (2022, 2022),
#         (2023, 2023),
#         (2024, 2024),
#         (2025, 2025),
#     )
#     years = forms.ChoiceField(choices=YEARS)
#     # models.Ceo.objects의 역할 도대체 무엇 >> return값인 ceoname만 반환했음
#     ceos = forms.ModelChoiceField(models.Ceo.objects)
#     #, widget=forms.Select(attrs={'pk':'ceoname'})) ModelChoiceField 뒤에 있던 아이인데 필요없는 것 같음.
#
#     # 초기데이터에서 값이 변했을 수도 있기 때문에 그 변환된 값으로 받아줌. 아래 정보 수정 부분에서 사용.
#     def clean_ceos(self):
#         checked_ceo = self.cleaned_data.get('ceos')
#         return checked_ceo
#
#     def clean_years(self):
#         checked_year = self.cleaned_data.get('years')
#         return checked_year
#
#
#
# # 회원가입 뷰(현재 admin에서만 사용)
# # 이게 없으면 왜 유저를 생성해도 로그인이 안되지?
# class UserCreationForm(forms.ModelForm):
#     password1 = forms.CharField(label='Password', widget=forms.PasswordInput)
#     password2 = forms.CharField(label='Password confirmation', widget=forms.PasswordInput)
#
#     class Meta:
#         model = MyUser
#         fields = '__all__'
#
#     def clean_password2(self):
#         password1 = self.cleaned_data.get("password1")
#         password2 = self.cleaned_data.get("password2")
#         if password1 and password2 and password1 != password2:
#             raise forms.ValidationError("Passwords don't match")
#         return password2
#
#     def save(self, commit=True):
#         user = super().save(commit=False)
#         user.set_password(self.cleaned_data["password1"])
#         if commit:
#             user.save()
#         return user
#
# # forms.ModelForm을 해줘야 모델과 연동이 되어 저장이 된다(+ 메타 클래스에 모델 선언)
# class CeoForm(forms.ModelForm):
#
#     class Meta:
#         model = Ceo
#         fields = ['ceoname', 'years', 'item_fields', 'work_fields', 'setup_fields', 'plus_points', 'itemname']
#
#     #수정된 데이터 받아오기(form.cleaned_data.get())
#     def clean_ceoname(self):
#         ceoname = self.cleaned_data.get('ceoname')
#         return ceoname
#     def clean_itemname(self):
#         itemname = self.cleaned_data.get('itemname')
#         return itemname
#     def clean_years(self):
#         years = self.cleaned_data.get('years')
#         return years
#     def clean_item_fields(self):
#         item_fields = self.cleaned_data.get('item_fields')
#         return item_fields
#     def clean_work_fields(self):
#         work_fields = self.cleaned_data.get('work_fields')
#         return work_fields
#     def clean_setup_fields(self):
#         setup_fields = self.cleaned_data.get('setup_fields')
#         return setup_fields
#     def clean_plus_points(self):
#         plus_points = self.cleaned_data.get('plus_points')
#         return plus_points
#
#     def save(self):
#         save = super().save(commit=True)
#
#
#
# # 기본 홈 뷰
# class HomeView(TemplateView):
#     #Listview에는 model명을 적지 않으면 에러남
#     # model = MyUser
#     template_name = 'django_ex/home.html'
#     # (listview를 상속받았을 경우)context_object_list의 디폴트 값은 object_list 또는 모델명소문자_list로 자동 지정된다.
#     # context_object_list =
#
# class BaseListView(TemplateView):
#     template_name = 'django_ex/base_info_list.html'
#
# def document_results(request, current_user, current_ceo):
#     forms = Ceo.objects.get(id=current_ceo)
#     ceo_score_info = Score.objects.get(myuser_id=current_user, ceo_id=current_ceo)
#     ceo_plus_score = Ceo.objects.get(ceo_relation=current_user, id=current_ceo)
#
#     sum_score = []
#     list = [ceo_score_info.score_0, ceo_score_info.score_1, ceo_score_info.score_2, ceo_score_info.score_3, ceo_score_info.score_4, ceo_score_info.score_5, ceo_score_info.score_6, ceo_score_info.score_7, ceo_score_info.score_8]
#     list_1 = [ceo_plus_score.plus_points]
#     sum_score.extend(list+list_1)
#
#     global middle_sum_score, final_sum_score
#     middle_sum_score = sum(list)
#     final_sum_score = sum(sum_score)
#     context = {
#         'show_score' : ceo_score_info,
#         'post' : forms,
#         'sum' : middle_sum_score,
#         'sum_score': final_sum_score
#     }
#     return render(request, 'django_ex/document_results.html', context)
#
#
# def document_post(request, current_user, current_ceo):
#     try:
#         # values_list('ceoname') 메서드를 사용하면 ceoname값만 불러오기 떄문에 템플릿에서 ceoname.id값을 호출하면 id에 대한 에러가 남.
#         ceo_instance = Ceo.objects.get(id=current_ceo)
#         myuser_instance = MyUser.objects.get(id=current_user)
#         check_exists = Score.objects.filter(myuser_id=myuser_instance.pk, ceo_id=ceo_instance.pk).exists()
#         # shell api를 이용해서 연구함, post할 때 ForeignKey값을 저장하는 방법, instance 매개변수 사용
#         foreign_instance = Score(myuser=myuser_instance, ceo=ceo_instance)
#
#         # 같은 평가자와 지원자의 정보가 이미 존재할 때 결과로 리다이렉트 한다.
#         if check_exists == True:
#             return redirect(reverse('django_ex:document_results', args=(current_user, current_ceo)))
#         else:
#             pass
#
#         if request.method == 'POST':
#             scoreform = ScoreForm(request.POST, instance=foreign_instance)
#             if scoreform.is_valid():
#                 scoreform.save()
#                 # 점수 저장이 완료되어 결과값을 볼 수 있는 화면으로 리다이렉트
#                 return HttpResponseRedirect(reverse('django_ex:document_results', args=(current_user, current_ceo)))
#             else:
#                 scoreform.errors
#         else:
#             scoreform = ScoreForm()
#
#         context = {
#             'post':ceo_instance,
#             'score':scoreform,
#         }
#
#         # 유효성 검사에 실패하였으므로 점수 입력하던 화면으로 리다이렉트(배점에 맞춰 입력해야함)
#         return render(request, 'django_ex/document_post.html', context)
#     except IntegrityError:
#         # unique_together옵션으로 평가자명과 지원자/기업명이 같으면 이미 평가가 완료된 상태를 뜻하기 떄문에 지원자 목록으로 리다이렉트 (check_exists를 생성한 이후로 불필요한 예외처리)
#         return redirect('django_ex:document_list', current_user)
#
#
# # ceoname을 서류평가 템플릿의 {% for in %} 태그에서 사용하기 위한 view

django_ex/templates/django_ex/base_info_reviews.html
{% extends 'base.html' %}
{% load staticfiles %}

{% block title %}competitor information{% endblock %}

{% block content %}
<div class="base-padding">
  <form class="" action="" method="post">
    {% csrf_token %}
    <ul>
      {% if ceos %}
      <tr>
        <td>해당연도 {{ceos.years}}</td>
        <td>지원자/기업명 {{ceos.ceos}}</td>
        <input type="submit" name="" value="검색">
      </tr>
    </ul>
    <table>
      {% if input_form %}
      {% if post %}
      <tr>
        <th>지원자/기업명</th>
        <td>{{post.ceoname}}</td>
        <th>창업유무</th>
        <td>{{post.setup_fields}}</td>
        <th>해당연도</th>
        <td>{{post.years}}년</td>
      </tr>
      <tr>
        <th>창업분야</th>
        <td>
        {{post.item_fields}}
      </td>
        <th>업종분야</th>
        <td>{{post.work_fields}}</td>
        <th>가점</th>
        <td>{{post.plus_points}}</td>
      </tr>
      <tr>
        <th>아이템명</th>
        <td colspan="5">{{post.itemname}}</td>
      </tr>
    </table>
  </form>
  {% endif %}
  {% endif %}
  {% endif %}
  <form action="{% url 'django_ex:base-info-change' post.id %}">
    <input type="submit" value="수정하기">
    </form>
</div>
{% endblock %}

django_ex/templates/django_ex/home.html
{% extends 'base.html' %}
{% load staticfiles %}
{% load filter %}
<!-- template 태그에는 has_group이란걸 갖고있지않다 -->

{% block header %}
<div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel">
  <ol class="carousel-indicators">
    <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
    <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
    <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
  </ol>
  <div class="carousel-inner" role="listbox">
    <!-- Slide One - Set the background image for this slide in the line below -->
    <div class="carousel-item active" style="background-image: url('http://retirement.miraeasset.com/common/namoeditor/binary/images/000013/1516753868908.jpg')">
      <div class="carousel-caption d-none d-md-block">
        <h3>미래가치를 디자인하는</h3>
        <p>창의실용교육중심대학</p>
      </div>
    </div>
    <!-- Slide Two - Set the background image for this slide in the line below -->
    <div class="carousel-item" style="background-image: url('http://retirement.miraeasset.com/common/namoeditor/binary/images/000013/1516753868908.jpg')">
      <div class="carousel-caption d-none d-md-block">
        <h3>가톨릭관동대학교</h3>
        <p>CATHOLIC KWANDONG UNIVERSITY</p>
      </div>
    </div>
    <!-- Slide Three - Set the background image for this slide in the line below -->
    <div class="carousel-item" style="background-image: url('http://retirement.miraeasset.com/common/namoeditor/binary/images/000013/1516753868908.jpg')">
      <div class="carousel-caption d-none d-md-block">
        <h3>중소벤처기업부</h3>
        <p>창업선도대학 육성사업 주관기관</p>
      </div>
    </div>
  </div>
  <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="sr-only">Previous</span>
  </a>
  <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="sr-only">Next</span>
  </a>
</div>
{% endblock %}

{% block content %}
<!-- Page Content -->
<div class="container">

  <h1 class="my-4">CATHOLIC KWANDONG UNIVERSITY</h1>

  <!-- Portfolio Section -->
  <h4>바로가기</h4>
  <div class="row">
    <div class="col-lg-4 col-sm-6 portfolio-item">
      <div class="card h-100">
        <a href=""><img class="card-img-top" src="{% static 'img/folder_1.png' %}" alt=""></a>
        <div class="card-body">
          <h4 class="card-title">
            {% if request.user|has_group:"manager" %}
            <a class="dropdown-item" href="{% url 'django_ex:base_info_list' %}">지원자 정보</a>
            {% elif user.is_authenticated %}
            <a class="dropdown-item" href="{% url 'django_ex:home' %}">지원자 정보</a>
            {% else %}
            <a class="dropdown-item" href="{% url 'login' %}">지원자 정보</a>
            {% endif %}
          </h4>
          <p class="card-text">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Amet numquam aspernatur eum quasi sapiente nesciunt? Voluptatibus sit, repellat sequi itaque deserunt, dolores in, nesciunt, illum tempora ex quae? Nihil, dolorem!</p>
        </div>
      </div>
    </div>
    <div class="col-lg-4 col-sm-6 portfolio-item">
      <div class="card h-100">
        <a href="#"><img class="card-img-top" src="{% static 'img/browser.png' %}" alt=""></a>
        <div class="card-body">
          <h4 class="card-title">
            {% if request.user|has_group_customuser:"customuser" %}
            <a class="dropdown-item" href="{% url 'django_ex:test_list' %}">발표평가</a>
            {% elif user.is_authenticated %}
            <a class="dropdown-item" href="{% url 'django_ex:home' %}">발표평가</a>
            {% else %}
            <a class="dropdown-item" href="{% url 'login' %}">발표평가</a>
            {% endif %}
          </h4>
          <p class="card-text">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam viverra euismod odio, gravida pellentesque urna varius vitae.</p>
        </div>
      </div>
    </div>
    <div class="col-lg-4 col-sm-6 portfolio-item">
      <div class="card h-100">
        <a href="#"><img class="card-img-top" src="{% static 'img/search.png' %}" alt=""></a>
        <div class="card-body">
          <h4 class="card-title">
            <!-- {% if request.user|has_group_customuser:"customuser" %}
            <a class="dropdown-item" href="#">2차 발표평가</a>
            {% elif user.is_authenticated %}
            <a class="dropdown-item" href="#">2차 발표평가</a>
            {% else %}
            <a class="dropdown-item" href="#">2차 발표평가</a>
            {% endif %} -->
          </h4>
          <p class="card-text">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Quos quisquam, error quod sed cumque, odio distinctio velit nostrum temporibus necessitatibus et facere atque iure perspiciatis mollitia recusandae vero vel quam!</p>
        </div>
      </div>
    </div>
    <!-- <div class="col-lg-4 col-sm-6 portfolio-item">
      <div class="card h-100">
        <a href="#"><img class="card-img-top" src="http://placehold.it/700x400" alt=""></a>
        <div class="card-body">
          <h4 class="card-title">
            <a href="#">Project Four</a>
          </h4>
          <p class="card-text">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam viverra euismod odio, gravida pellentesque urna varius vitae.</p>
        </div>
      </div>
    </div>
    <div class="col-lg-4 col-sm-6 portfolio-item">
      <div class="card h-100">
        <a href="#"><img class="card-img-top" src="http://placehold.it/700x400" alt=""></a>
        <div class="card-body">
          <h4 class="card-title">
            <a href="#">Project Five</a>
          </h4>
          <p class="card-text">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam viverra euismod odio, gravida pellentesque urna varius vitae.</p>
        </div>
      </div>
    </div>
    <div class="col-lg-4 col-sm-6 portfolio-item">
      <div class="card h-100">
        <a href="#"><img class="card-img-top" src="http://placehold.it/700x400" alt=""></a>
        <div class="card-body">
          <h4 class="card-title">
            <a href="#">Project Six</a>
          </h4>
          <p class="card-text">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Itaque earum nostrum suscipit ducimus nihil provident, perferendis rem illo, voluptate atque, sit eius in voluptates, nemo repellat fugiat excepturi! Nemo, esse.</p>
        </div>
      </div> -->
    <!-- </div> -->
  </div>
  <!-- /.row -->

  <!-- Features Section -->
  <!-- <div class="row">
    <div class="col-lg-6">
      <h2>Modern Business Features</h2>
      <p>The Modern Business template by Start Bootstrap includes:</p>
      <ul>
        <li>
          <strong>Bootstrap v4</strong>
        </li>
        <li>jQuery</li>
        <li>Font Awesome</li>
        <li>Working contact form with validation</li>
        <li>Unstyled page elements for easy customization</li>
      </ul>
      <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Corporis, omnis doloremque non cum id reprehenderit, quisquam totam aspernatur tempora minima unde aliquid ea culpa sunt. Reiciendis quia dolorum ducimus unde.</p>
    </div>
    <div class="col-lg-6">
      <img class="img-fluid rounded" src="http://placehold.it/700x450" alt="">
    </div>
  </div> -->
  <!-- /.row -->

  <hr>

  <!-- Call to Action Section -->
  <!-- <div class="row mb-4">
    <div class="col-md-8">
      <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Molestias, expedita, saepe, vero rerum deleniti beatae veniam harum neque nemo praesentium cum alias asperiores commodi.</p>
    </div>
    <div class="col-md-4">
      <a class="btn btn-lg btn-secondary btn-block" href="#">Call to Action</a>
    </div>
  </div> -->

</div>
<!-- /.container -->
{% endblock %}

django_ex/templates/django_ex/test_list.html
{% extends 'base.html' %}
{% load staticfiles %}
{% load filter %}

{% block title %}1차 발표평가 정보 보기{% endblock %}

{% block content %}
<div class="base-padding">
  <ul>
    <li>
      {% if request.user|has_group_customuser:"customuser" %}
      <!-- <a class="" href="{% url 'django_ex:document_list' user.id %}">평가하기</a> -->
      <a class="" href="{% url 'django_ex:select_year' %}">평가하기</a>
      {% elif user.is_authenticated %}
      <a class="" href="{% url 'django_ex:home' %}">평가하기</a>
      {% else %}
      <a class="" href="{% url 'login' %}">평가하기</a>
      {% endif %}
    </li>
    <li>
      {% if request.user|has_group_customuser:"customuser" %}
      <a class="" href="{% url 'django_ex:select_year_results' %}">평가 결과 보기</a>
      {% elif user.is_authenticated %}
      <a class="" href="{% url 'django_ex:home' %}">평가 결과 보기</a>
      {% else %}
      <a class="" href="{% url 'login' %}">평가 결과 보기</a>
      {% endif %}
    </li>
  </ul>
</div>
{% endblock %}

django_ex/templates/django_ex/test_list_1.html
{% extends 'base.html' %}
{% load staticfiles %}

{% block title %}1차 발표평가 평가하기{% endblock %}

{% block content %}
<div class="base-padding">
  <form class="" action="{% url 'django_ex:select_year' %}" method="post">
    {% csrf_token %}
    <ul>
      {% if ceo_list %}
      {% for list in ceo_list %}
      <li>
        <a href="{% url 'django_ex:document_post' user.id list.id %}">{{list.ceoname}}님의 발표평가</a>
      </li>
      {% endfor %}
      {% endif %}
    </ul>
  </form>
</div>
{% endblock %}